services:
  backend:
    build:
      context: ./backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    environment:
      # - DB_HOST=mysql
      # - DB_PORT=3306
      # - DB_DATABASE=laravel
      # - DB_USERNAME=root
      # - DB_PASSWORD=root
      - APP_ENV: production
      - APP_KEY: base64:IaYGqEqLvtsOegNgR5oAnAvUy6/JU/MIwUU2KF1NJik=
      - APP_URL: ${RAILWAY_STATIC_URL}
      - DB_HOST: ${MYSQLHOST}
      - DB_PORT: ${MYSQLPORT}
      - DB_DATABASE: ${MYSQLDATABASE}
      - DB_USERNAME: ${MYSQLUSER}
      - DB_PASSWORD: ${MYSQLPASSWORD}
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/frontend
    networks:
      - app_network

  # phpmyadmin:
  #       image: phpmyadmin/phpmyadmin
  #       ports:
  #           - "9999:80"
  #       environment:
  #           PMA_HOST: mysql
  #           PMA_USER: root
  #           PMA_PASSWORD: root
  #       networks:
  #           - app_network
  #       depends_on:
  #           - mysql

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
