version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:IaYGqEqLvtsOegNgR5oAnAvUy6/JU/MIwUU2KF1NJik=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=railway
      - DB_USERNAME=root
      - DB_PASSWORD=tPwuDwVMmRTdIzTRwzBQBYVzuZEgatdC
    volumes:
      - .:/var/www
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: tPwuDwVMmRTdIzTRwzBQBYVzuZEgatdC
    ports:
      - "3306:3306"
