[phases.setup]
commands = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
commands = [
  "php artisan config:cache",
  "php artisan route:cache"
]

[phases.start]
commands = [
  "php artisan serve --host=0.0.0.0 --port=8000"
]

[variables]
PORT = "8000"
